## 
##  Created on: Mai 27, 2010
##      Author: martinez
##
##  $Id: FindANTTWEAKBAR.cmake 105 2011-04-12 11:47:23Z martinez $

FIND_PATH(ANTTWEAKBAR_INCLUDE_DIR AntTweakBar.h PATHS extern/include)
if (CMAKE_CL_64)
   FIND_LIBRARY(ANTTWEAKBAR_LIBRARY AntTweakBar64 PATHS extern/x64) 
else()
   FIND_LIBRARY(ANTTWEAKBAR_LIBRARY AntTweakBar PATHS extern/x86) 
endif()

SET(ANTTWEAKBAR_FOUND FALSE)
IF (ANTTWEAKBAR_INCLUDE_DIR AND ANTTWEAKBAR_LIBRARY)
   SET(ANTTWEAKBAR_FOUND TRUE)
ENDIF (ANTTWEAKBAR_INCLUDE_DIR AND ANTTWEAKBAR_LIBRARY)

IF (ANTTWEAKBAR_FOUND)
   IF (NOT ANTTWEAKBAR_FIND_QUIETLY)
      MESSAGE(STATUS "Found AntTweakBar: ${ANTTWEAKBAR_INCLUDE_DIR} ${ANTTWEAKBAR_LIBRARY}")
   ENDIF (NOT ANTTWEAKBAR_FIND_QUIETLY)
ELSE (ANTTWEAKBAR_FOUND)
   IF (ANTTWEAKBAR_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find AntTweakBar ${ANTTWEAKBAR_LIBRARY} ${ANTTWEAKBAR_INCLUDE_DIR}")
   ELSE  (ANTTWEAKBAR_FIND_REQUIRED)
      MESSAGE(STATUS "Could not find AntTweakBar ${ANTTWEAKBAR_LIBRARY} ${ANTTWEAKBAR_INCLUDE_DIR}")
   ENDIF (ANTTWEAKBAR_FIND_REQUIRED)
ENDIF (ANTTWEAKBAR_FOUND)

# :mode=cmake:
